### ISSUE TITLE
How to apply remote server and other arguments

### ISSUE THREAD

**Issue by mkjaxxo** [jxmorris12/language_tool_python#1]
Hi, 
is there a way to add arguments  to this interpreter call? Thanks for your help. 

> import language_tool_python
> tool = language_tool_python.LanguageTool('en-US')
> text = u'A sentence with a error in the Hitchhiker’s Guide tot he Galaxy'
> matches = tool.check(text)
> len(matches)

**Comment by jxmorris12** [comment]
Hi @mkjaxxo,

I added some information about this to the documentation, and updated the code to make it a bit easier. Basically, you can do something like this:

    tool = language_tool_python.LanguageTool('en-US', remote_server='api.mkjaxxo.net')

and replace the `api.mkjaxxo.net` URL with your actual remote URL.

However, if what you're trying to do is query the public LT API, that's even easier:

    tool = language_tool_python.LanguageToolPublicAPI('en-US')

Hope one of those helps you find what you're looking for!

**Comment by mkjaxxo** [comment]
This is very usefull. Thanks @jxmorris12 for your fast reply.
