### ISSUE TITLE
NameError: name 'ElementTree' is not defined

### ISSUE THREAD

**Issue by melanatech** [jxmorris12/language_tool_python#11]
I tried importing Element Tree and it's still not found. I can't find the dependency import in your code either. the language-check package works just fine, so not sure what's the problem here if this is a fork.

tool = language_tool_python.LanguageTool('en-US')

```
Traceback (most recent call last):

  File "<ipython-input-121-a8b75bd4f267>", line 1, in <module>
    tool = language_tool_python.LanguageTool('en-US')

  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 44, in __init__
    self._start_server_on_free_port()

  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 188, in _start_server_on_free_port
    self._start_local_server()

  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 252, in _start_local_server
    tree = ElementTree.parse(f)

NameError: name 'ElementTree' is not defined
```

**Comment by jxmorris12** [comment]
Hi @melanatech --

Ok, first of all thanks providing me with a detailed error, and thanks for using language_tool_python. I think this error occurred because the LTP default port (8081) was taken on your machine. You're right that `ElementTree` is from the old version (`language-check`) and I'd missed that reference when I ported the code over for the new Python & LanguageTool versions!

Anyways, I fixed it, and pushed a new version: `2.2.4`. Reinstall (`pip install language_tool_python --upgrade`) and try whatever you were doing again! If that didn't fix it let me know and I'll keep trying!

**Comment by melanatech** [comment]
Thanks for responding so quickly. No more ElementTree error! But I did get a different error when testing a string.


```
import language_tool_python
tool = language_tool_python.LanguageTool('en-US')

matches = tool.check('cz of this brand is awsome,,i love this brand very much')

tool.correct('cz of this brand is awsome,,i love this brand very much', matches)
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-15-943a43c2ebc1>", line 1, in <module>
>     tool.correct('cz of this brand is awsome,,i love this brand very much', matches)
> 
>   File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 121, in correct
>     return correct(text, self.check(text, srctext))
> 
>   File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 97, in check
>     response = self._get_root(url, self._encode(text, srctext))
> 
>   File "/Users/xxx/anaconda3/lib/python3.7/site-packages/language_tool_python/server.py", line 104, in _encode
>     params['srctext'] = srctext.encode('utf-8')
> 
> AttributeError: 'list' object has no attribute 'encode'

**Comment by jxmorris12** [comment]
welp, this is progress! thanks again @melanatech  I'll get back to you soon

**Comment by jxmorris12** [comment]
Hi @melanatech! I fixed the problem, I think! And I added tests so this won't happen again. Thanks for being patient!

**Comment by melanatech** [comment]
Thanks for working on this @jxmorris12. I'd been using the old language-check, but I'm just now coming back and realizing that I still got the most recent issue. It looks like the mains reason it happens is because I'm supplying a "matches" variable in the function when it's only allowing "text". 

In my code, I'm creating a custom match list from the Match object because there are only certain rules that I want applied. Any plans to allow custom correction? Or is it better to just define my own correction function?

**Comment by jxmorris12** [comment]
Hi @melanatech!! I changed the API a little bit from `language-check`, but we do still have that functionality. If you want to correct string `s` with a `List[Match]` `matches`, use this:

```language_tool_python.utils.correct(s, matches)```

I'm going to add this to the README now!

**Comment by melanatech** [comment]
Ok, great. Thank you!
