### ISSUE TITLE
Clarify the License

### ISSUE THREAD

**Issue by Julian** [jxmorris12/language_tool_python#12]
Hi there. Thanks for taking over maintenance of this, it looks quite useful.

The previous fork is/was [licensed under the LGPL](https://github.com/myint/language-check/blob/master/COPYING).

I see here the code seems to now say the repository is [licensed under the MIT license](https://github.com/jxmorris12/language_tool_python/blob/502443908f085c20d4ad8966c3f3f470c0cc6cbe/setup.py#L17) with no mention of LGPL.

I do see some code (probably quite a bit) that remains from the original repository and which therefore in those sections seems to be LGPL licensed.

Can you clarify whether you have permission from the original authors to relicense the code under the MIT license or whether in fact the code remains under the LGPL?

Thanks!

**Comment by jxmorris12** [comment]
Well, there is actually very little code that remains from the original repository. That said, the GNU General Public License seems reasonable, and I've added it to the repository. Sorry about that.

**Comment by Julian** [comment]
No no, all good!

Just wanted to make sure.

Also, the original repository seems to allow *either* GPL or LGPL -- so any code from there in theory anyone is free to choose between the two of those. Any code written afterwards certainly can be MIT (but you can now change to GPL certainly as well). But certainly saying it's all GPL going forward at least resolves the license on any code taken from the original repo.

(IANAL, etc.)

And thanks for responding so quickly!

**Comment by jxmorris12** [comment]
Np @Julian! what are the advantages of GPL vs LGPL? which would you recommend?

**Comment by Julian** [comment]
It's a very personal (and polarizing, and political, and etc. issue).

Personally I, as you had it, use MIT for all my projects, but the issue I was clarifying here was around not being able to retroactively apply that license to code that was written under the older licenses.

If you want to avoid the question entirely (as I'm kind of avoiding answering :) -- you also can just do as the original repository did, and include *both* licenses (i.e. dual license under GPL and LGPL, as the original library did)

For the setup.py you pick one, whichever one, but you can have 2 COPYING files the same way the original repo did?

**Comment by Julian** [comment]
I guess I answered that as a more broad question than you asked (which was more LGPL vs GPL, not vs anything else) -- but if you want some more info on the difference between GPL and LGPL, https://choosealicense.com/licenses/lgpl-3.0/ which is what GitHub uses has some plaintext explanation)
