### ISSUE TITLE
Changes the names of persons in the given texts

### ISSUE THREAD

**Issue by D-i-l-r-u-k-s-h-i** [jxmorris12/language_tool_python#15]
The spell correction algorithm in this library changes the person names, when a text sequence(sentence) is submitted for correction. How can I prevent that?

**Comment by jxmorris12** [comment]
can you provide an example?

**Comment by D-i-l-r-u-k-s-h-i** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/47185867/88759679-eec70800-d188-11ea-9c03-a24d0ad0f179.png">

**Comment by jxmorris12** [comment]
Hi @D-i-l-r-u-k-s-h-i -- thanks for providing an example. I tested this a bit– it seems that, annoyingly, LanguageTool counts these as spelling errors. See the following screenshot from languagetool.org:

<img width="982" alt="Screen Shot 2020-08-11 at 2 16 25 PM" src="https://user-images.githubusercontent.com/13238952/89933584-40d24980-dbdd-11ea-8f78-bcd46e119cf9.png">

**Comment by jxmorris12** [comment]
@D-i-l-r-u-k-s-h-i  (continued) there are two options here.

1. (easier) just disable spellchecking. If you call `tool.disable_spellchecking()` before `tool.correct` in your example above, these names won't be corrected. Here's an example:

```
>>> s = "Department of medicine Colombia University closed on August 1 Milinda Samuelli"
>>> import language_tool_python
>>> tool = language_tool_python.LanguageTool('en-US')
>>> tool.disable_spellchecking()
>>>
>>> tool.check(s)
[]
>>> tool.enable_spellchecking()
>>>
>>> tool.check(s)
[Match({'ruleId': 'MORFOLOGIK_RULE_EN_US', 'message': 'Possible spelling mistake found.', 'replacements': ['Melinda', 'Malinda'], 'context': '... Colombia University closed on August 1 Milinda Samuelli', 'offset': 62, 'errorLength': 7, 'category': 'TYPOS', 'ruleIssueType': 'misspelling'}), Match({'ruleId': 'MORFOLOGIK_RULE_EN_US', 'message': 'Possible spelling mistake found.', 'replacements': ['Samuel'], 'context': '...a University closed on August 1 Milinda Samuelli', 'offset': 70, 'errorLength': 8, 'category': 'TYPOS', 'ruleIssueType': 'misspelling'})]
```

2. (harder) filter out spellchecking rules that you don't like – one easy way is to ignore words that are corrected, and uppercase. (This has the immediate disadvantage that any words that are capitalized to indicate the beginning of a sentence will not be corrected. If you can come up with a better scheme to determine whether a given word is a name, that would be preferred.) Anyways, this could look something like:

```
>>> s = "Department of medicine Colombia University closed on August 1 Milinda Samuelli"
>>> is_bad_rule = lambda rule: rule.message == 'Possible spelling mistake found.' and len(rule.replacements) and rule.replacements[0][0].isupper()
>>> import language_tool_python
>>> tool = language_tool_python.LanguageTool('en-US')
>>> matches = tool.check(s)
>>> matches = [rule for rule in matches if not is_bad_rule(rule)]
>>> language_tool_python.utils.correct(s, matches)
'Department of medicine Colombia University closed on August 1 Melinda Samuel'
```

Here, I defined `is_bad_rule`, a short function that determines if a rule is 'bad', namely if it (1) is correcting spelling and (2) recommends a replacement word that is capitalized. Again, you can likely come up with a better way, but this works. The code calls `language_tool_python.utils.correct`, a helper function that takes a string and list of `Match` objects (errors detected by LanguageTool) and returns the string with errors corrected.

Hope that helps you fix your error!

**Comment by D-i-l-r-u-k-s-h-i** [comment]
@jxmorris12,  Thank you.
