### ISSUE TITLE
Include LIGATURES in _spell_checking_rules

### ISSUE THREAD

**Issue by matthewmcintire** [jxmorris12/language_tool_python#16]
`LIGATURES` is a spelling rule. Please include it in `LanguageTool._spell_checking_rules`

**Comment by matthewmcintire** [comment]
Or perhaps `disable_spellchecking` should add `TYPOS` to `disabled_categories` instead of compiling a list of rules. `TYPOS` is defined as "Spelling issues".

**Comment by matthewmcintire** [comment]
I opened a pull request. Not sure what's going on with the Spanish test, though

**Comment by jxmorris12** [comment]
I merged it – thank you! I'll fix the tests later
