### ISSUE TITLE
Upgrade the Langugage Tool Default version

### ISSUE THREAD

**Issue by misrasaurabh1** [jxmorris12/language_tool_python#18]
I see that the default Language Tool version is 4.9 whereas the latest Language Tool version is 5.0.1.
https://github.com/jxmorris12/language_tool_python/blob/3b290d54406bb3034308f3e60bb625eda4e293e6/language_tool_python/download_lt.py#L31

Could the default Language tool version be upgraded to the latest one?

Thanks!

**Comment by jxmorris12** [comment]
@misrasaurabh1 thanks for bringing this to my attention! It's weird– I thought I'd subscribed to the schedule of new updates, but I guess I missed this one. Anyway, I updated and pushed a new version to PyPI (ltp 2.4.0) that should be compatible with LanguageTool 5.0. 

In the future, I'll try to be more punctual. The longterm solution would be to determine the most recent version via web request and download it if necessary. Let me know if you have an idea on how to do something like that.

**Comment by danielnaber** [comment]
> The longterm solution would be to determine the most recent version via web request and download it if necessary.

The latest version is always the one at https://languagetool.org/download/LanguageTool-stable.zip in case that helps.

**Comment by jxmorris12** [comment]
thanks @danielnaber !
