### ISSUE TITLE
How to add new words to the vocabulary of this tool?

### ISSUE THREAD

**Issue by kapilg1997** [jxmorris12/language_tool_python#21]
Hi I am new to NLP in general. I want to implement this tool as a spell checker. How to add new words in the existing vocabulary of this tool?

**Comment by kapilg1997** [comment]
Sorry, this is not working

(base) D:\Work files\corrected>python post_process.py 2715_11438280.txt
self._url: https://api.languagetool.org/v2/
Traceback (most recent call last):
  File "post_process.py", line 16, in <module>
    matches = [rule for rule in matches if not is_correctly_spelled(rule)]
  File "post_process.py", line 16, in <listcomp>
    matches = [rule for rule in matches if not is_correctly_spelled(rule)]
  File "post_process.py", line 7, in <lambda>
    is_correctly_spelled = lambda rule: rule.ruleIssueType == 'misspelling' and rule.matchedText in vocab
  File "C:\ProgramData\Anaconda3\lib\site-packages\language_tool_python\match.py", line 107, in __getattr__
    .format(self.__class__.__name__, name))
AttributeError: 'Match' object has no attribute 'matchedText'

**Comment by jxmorris12** [comment]
@kapilg1997 It seems your version is outdated. Can you try `pip install language_tool_python --upgrade` please?

**Comment by kapilg1997** [comment]
> @kapilg1997 It seems your version is outdated. Can you try `pip install language_tool_python --upgrade` please?

Works now thanks!!

**Comment by jxmorris12** [comment]
@Ierezell -- a pull request would be wonderful! Please consider it!
