### ISSUE TITLE
[super minor issue] Link to languagetool.org on PyPi page is broken 

### ISSUE THREAD

**Issue by Henriii** [jxmorris12/language_tool_python#22]
The text on the [pypi page](https://pypi.org/project/language-tool-python/) reads:
`This is a Python wrapper for LanguageTool. `

Clicking on the word `LanguageTool` does not direct to the expected page.

**Current behaviour:**
The link on `LanguageTool` directs to https://pypi.org/project/language-tool-python/languagetool.org/

**Expected behaviour:**
The link on `LanguageTool` directs to https://languagetool.org/

**Comment by jxmorris12** [comment]
Thanks!
