### ISSUE TITLE
Is there the possibility to use a proxy server with this?

### ISSUE THREAD

**Issue by Leo-Strijbos** [jxmorris12/language_tool_python#23]
Hi all,
I am using this library on a rest API on pythonanywhere. However, this requires me to use a proxy server. Is this possible?
Thanks

**Comment by jxmorris12** [comment]
@Leo-Strijbos I don't think I understand your question. LanguageTool works like any other server, so should handle requests that have been routed through a proxy server just like it handles normal requests.

**Comment by Leo-Strijbos** [comment]
Can you add the possibility to access the API through the languagetool.org/api/v2 URL rather than the api.languagetool.org/v2 URL. I am hosting a rest API on pythonanywhere, and they won't add this API to the whitelist unless it goes through the official URL. Thanks

**Comment by Leo-Strijbos** [comment]
It's in the line 274 of server.py file

**Comment by jxmorris12** [comment]
Sure. I didn't know the difference between these two URLs.

**Comment by Leo-Strijbos** [comment]
api.languagetool.org is not mentioned in the documentation, so the guys at python anywhere wont add it to the api whitelist

**Comment by Leo-Strijbos** [comment]
Can you also add it to pypi.org so that I can download the new version through pip

**Comment by jxmorris12** [comment]
I think I fixed this in the latest version, 2.4.3. Let me know if you are still having trouble!!
