### ISSUE TITLE
Debug mode true

### ISSUE THREAD

**Issue by jinyongyoo** [jxmorris12/language_tool_python#25]
Hey Jack, it seems that debug mode is set to true in https://github.com/jxmorris12/language_tool_python/blob/master/language_tool_python/server.py. This is causing TextAttack tests to fail since extraneous debug statements are getting printed. 

![Screen Shot 2020-10-06 at 12 26 22 PM](https://user-images.githubusercontent.com/32072203/95229951-33959d80-07cf-11eb-9ca2-1a8886c5d423.png)

**Comment by jxmorris12** [comment]
fixed in 2.4.5!! sorry about that!
