### ISSUE TITLE
'Match' object has no attribute 'length'

### ISSUE THREAD

**Issue by danieljue** [jxmorris12/language_tool_python#3]
Unable to iterate through matches list and print the objects (or print an individual match) because length is not being used.

Input
`m = tool.check('All of the deaths have occurred in Washington state')
print (m[0])`

Output:

> AttributeError                            Traceback (most recent call last)
<ipython-input-22-0328f9d8a611> in <module>
      1 m = tool.check('All of the deaths have occurred in Washington state')
----> 2 print (m[0])
>/env/lib/python3.8/site-packages/language_tool_python/match.py in __str__(self)
     76         ruleId = self.ruleId
     77         s = 'Offset {}, length {}, Rule ID: {}'.format(
---> 78             self.offset, self.length, ruleId)
     79         if self.message:
     80             s += '\nMessage: {}'.format(self.message)
>/env/lib/python3.8/site-packages/language_tool_python/match.py in __getattr__(self, name)
    104     def __getattr__(self, name):
    105         if name not in get_match_ordered_dict():
--> 106             raise AttributeError('{!r} object has no attribute {!r}'
    107                                  .format(self.__class__.__name__, name))
>AttributeError: 'Match' object has no attribute 'length'

**Comment by jxmorris12** [comment]
Hi @danieljue. Thanks for noticing this - looks like it's a bug that was introduced in our most recent update. I pushed a new version, `2.1.1`, where this issue should be fixed.

Can you try upgrading (`pip install language_tool_python --upgrade`) and let me know if the issue persists?

**Comment by jeanthom** [comment]
Hi, I had the same issue as @danieljue and the issue now seems to be fixed with the latest update. Thanks!

**Comment by jxmorris12** [comment]
Thanks @jeanthom! Happy to help.

@danieljue gonna close the issue for now. feel free to re-open if you're still having problems.
