### ISSUE TITLE
Please add tqdm as dependency

### ISSUE THREAD

**Issue by TheJackiMonster** [jxmorris12/language_tool_python#39]
I was trying to get language_tool_python working under ArchLinux but I had to install python-tqdm first, otherwise importing failed.

By the way I have also created a package in the [AUR](https://aur.archlinux.org/packages/python-languagetool-git/) for language_tool_python because I have integrated it as optional spellchecker to Manuskript now and needed a convenient way to install. Keep up the good work. ^^

**Comment by TheJackiMonster** [comment]
Nevermind I found it in the requirements.txt.

**Comment by jxmorris12** [comment]
Thanks for the feedback though @TheJackiMonster !
