### ISSUE TITLE
language_tool_python actually requires Python3 >= Python 3.6

### ISSUE THREAD

**Issue by Vbbab** [jxmorris12/language_tool_python#4]
The installed language_tool_python library from pip / Github uses f-strings, which, according to [this answer](https://stackoverflow.com/a/50401698/10454097) was only introduced in Python 3.6.

**Comment by Vbbab** [comment]
And [this page](https://www.python.org/dev/peps/pep-0498/) on the Python website also states so.

**Comment by Vbbab** [comment]
Please update the README. The current requisites say:
`Python 3.3+ <https://www.python.org>`

**Comment by jxmorris12** [comment]
There's actually only a single f-string, in an error that kills the program. I removed it and pushed a new version, `2.1.2`. If you're still having issues, feel free to re-open the issue.
