### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Ierezell** [jxmorris12/language_tool_python#41]
Hi, 

I was playing with the package (which is really nice btw ! thanks) and I found that some mistakes don't have replacements, but there are replacements with the online tester (https://languagetool.org/fr). 

One is about plural, `wordX wordY` which propose => `wordX_plural wordY_plural` or `wordX_sing wordY_sing`. 

However when using it with the python package I don't get this replacements (it's just empty).

Could it come from a more recent version (5.4 online) than the package one (5.1)? 
If yes could you please update it ? 

Else, could you point me in the direction to have this type of corrections  in the python package ? 

Thanks a lot, 

Have a great day.

**Comment by jxmorris12** [comment]
Thanks for the update @Ierezell -- I didn't realize that our LanguageTool version was out of date! It looks like the most recent is 5.3 -- hope that's correct. I'm updating the package now; please let me know if your issues persist and I'll look more into it!

**Comment by jxmorris12** [comment]
just updated

**Comment by Matthieu-Tinycoaching** [comment]
@jxmorris12 Could you update the LanguageTool version to 5.4. Indeed, when automatically loading with `tool = language_tool_python.LanguageTool('en-US')` command I got the 5.3 only version?

Thanks!

**Comment by jxmorris12** [comment]
@Matthieu-Tinycoaching thanks for letting me know! I just build & released a new version which should include LanguageTool 5.4.

**Comment by Matthieu-Tinycoaching** [comment]
@jxmorris12 I just relaunched the command line to automatically download LanguageTool but it still 5.3.
