### ISSUE TITLE
urllib Forbidden 403 when retrieving English language

### ISSUE THREAD

**Issue by XuanChau** [jxmorris12/language_tool_python#42]
I believe this is a similar issue to this: https://github.com/myint/language-check/issues/25

I've been getting the following error when running the line `tool = language_tool_python.LanguageTool('en-US')` during my Docker build:

![image](https://user-images.githubusercontent.com/28720334/129810297-f96ff6a7-8ac8-42ba-a3bb-6af0956eec9d.png)

I've looked into this specific urllib error. Most suggest this is a web-scrape prevention mechanism of websites, but the LanguageTool .jar server wouldn't care about that. 

The strangest thing is that this Docker build _works_ when I build in my company's main VPN, but fails when I build in my company's specialized VPN. I'd assume that the LanguageTool .jar server isn't being installed correctly on the specialized network, but the stack trace implies that LanguageTool was installed just fine and is running. It's just the urllib 403 forbidden error that happens afterwards when querying the server for `http://127.0.0.0:8081/v2/languages`. I presume all other attempts to query the language server would result in the same issue. 

Some details:
1. OS is Debian GNU/Linux 11.0
2. Python version 3.8
3. Java 11.0 JVM
4. language_tool_python version 2.5.4, installing LanguageTool server version 5.3

I can provide any other info as needed. I think I've exhausted all attempts to fix this issue though...

**Comment by jxmorris12** [comment]
Thanks for reporting @XuanChau! Can you check and make sure that your `language_tool_python` is up-to-date? (just `pip install language_tool_python --upgrade`)

I'm pretty sure this error will persist, which means i'll have to look into it, and I should have some time to do so tomorrow. But I saw in your screenshot that you're running LanguageTool version 5.3, which is I think a little outdated at this point.

**Comment by jxmorris12** [comment]
Hi @XuanChau - this should be definitively fixed now. Let me know if something isn't working with 2.6.1
