### ISSUE TITLE
Create a async version for the library 

### ISSUE THREAD

**Issue by bensonchow123** [jxmorris12/language_tool_python#44]
This will be really useful for discord developers if there is a async version of it

**Comment by jxmorris12** [comment]
Sorry, @bensonchow123, I don't know what you mean.

**Comment by jxmorris12** [comment]
@bensonchow123 is it a speed issue (i.e. the tool is running too slowly)? Otherwise, can't you just wrap calls to the library using something like [asyncio](https://docs.python.org/3/library/asyncio.html)?

**Comment by jxmorris12** [comment]
Let me know if you want me to reopen and we can discuss.
