### ISSUE TITLE
how can we know the list of all the error categories for a language (say French)?

### ISSUE THREAD

**Issue by xiaoouwang** [jxmorris12/language_tool_python#47]
I guess the total number and list of error categories are specific for each language. Is there a way to get such a list for each language?

Fantastic work by the way :D

**Comment by jxmorris12** [comment]
Hi @xiaoouwang -- there are many error categories for each language, and they're scattered throughout the LanguageTool source code. I don't know of a way to get that information, unfortunately.

I did find this (outdated) list of errors for the English language: https://gist.github.com/Pwootage/1227131

**Comment by xiaoouwang** [comment]
Tks it helps greatly! I think there are two kinds of rules introduced in
langtool. The Java rules should be extractable. Will take a look into it.

**Comment by jxmorris12** [comment]
Good luck! Do let us know if you find how to do it in a scalable way!

**Comment by bMorgan01** [comment]
I know this is ancient, but I went looking for the same information and found this [page](https://community.languagetool.org/rule/list?lang=en&offset=30&max=10). It includes multiple languages and the category for every error rule LanguageTool uses. Hopefully this helps someone in the future!
