### ISSUE TITLE
language_tool_python.utils.ServerError: Server running; don't start a server here

### ISSUE THREAD

**Issue by zxk19981227** [jxmorris12/language_tool_python#49]
when i tries to use this model to correct a sentence, a problem occurs that
 `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zxk/.conda/envs/clean_label/lib/python3.7/site-packages/language_tool_python/server.py", line 55, in __init__
    self._start_server_on_free_port()
  File "/home/zxk/.conda/envs/clean_label/lib/python3.7/site-packages/language_tool_python/server.py", line 225, in _start_server_on_free_port
    self._start_local_server()
  File "/home/zxk/.conda/envs/clean_label/lib/python3.7/site-packages/language_tool_python/server.py", line 283, in _start_local_server
    raise ServerError('Server running; don\'t start a server here.')
language_tool_python.utils.ServerError: Server running; don't start a server here.
`
when I execute the command `tool = language_tool_python.LanguageTool('en-US')`
how could this happen?

**Comment by jxmorris12** [comment]
Well @zxk19981227, this is a doozy. As far as I'm aware, this can only happen if every port on your machine from 8081 to 8999 is taken. The `ServerError` you're observing is supposed to be caught in the [`_start_server_on_free_port`](https://github.com/jxmorris12/language_tool_python/blob/master/language_tool_python/server.py#L221-L231) method. It's only used when the port is taken, to increment the port number until we find a free port.

Can you check to see if your ports are really all taken? That seems surprising. You can see open ports on linux with this command: `sudo lsof -i -P -n`. 

For example, I just started two language_tool_python servers (to check to make sure the port-incrementing logic was working properly) and I can see them here: 

```bash
> sudo lsof -i -P -n | grep java
java      11697     jxmorris12  130u  IPv6 0x48b21c98491e70c7      0t0    TCP 127.0.0.1:8081 (LISTEN)
java      11768     jxmorris12  130u  IPv6 0x48b21c984b641da7      0t0    TCP 127.0.0.1:8082 (LISTEN)
```

If I were to start a third language_tool_python server, it'd raise and catch two ServerErrors before settling on 8083 as an open port.

One more thing: It seems unlikely you have a good reason to keep something running on all 918 ports from 8081 to 8999. However, if you do need to change the port for some reason, you can edit MIN_PORT and MAX_PORT in server.py: https://github.com/jxmorris12/language_tool_python/blob/master/language_tool_python/server.py#L36-L37

**Comment by zxk19981227** [comment]
Thank you for your reply. I see the port used on the machine I used but only 8081 and 8085 are used by others. I didn't successfully solve the problem on the original machine but I solve it by moving it to another machine.
