### ISSUE TITLE
Use locally downloaded language tool instead of downloading it from url?

### ISSUE THREAD

**Issue by asnashafiq** [jxmorris12/language_tool_python#53]
When using the local server, there is a download from a url for the language tool during initialization. Is it possible to add a local configuration that lets you use an already downloaded tool under `LTP_PATH` and bypass the download code? Wondering if there's a way to bypass the download from the url with 100% certainty.

**Comment by Zhao-Qiao** [comment]
I wonder if you have solved this problem? I've been trying to use a locally stored Language Tool as the local server so that my python scripts can run totally offline. But sadly I don't know how to configure it. I've tried to replace LTP_PATH with a path to my project but it didn't work.

**Comment by Dabirius** [comment]
I had the same issue. For me the following worked:

pip download the installation files on a device with internet connection. Then use these files on the device without internet connection to pip install the module (!pip install language_tool_python --no-index --find-links=file:///PATHTOINSTALLFILES). 

To avoid that the python import of the module tries to download LanguageTool{version}.zip and put it in the cache of your device, you need to download the LanguageTool{version}.zip on another device with internet connection (from here https://languagetool.org/download/?C=S;O=D) and always (if cache gets deleted after usage) move these files in the cache of your offline device before importing the module. I used this command: !mv {unzipped folder which needs to be moved to cache} {path to your cache} inside my python script before the import function.

Hope that helps!

**Comment by pyagoubi** [comment]
I'm having the same issue
I tried your solution but it doesnt work. Could it be that your first step, I have to make slightly different? Instead of
!pip install language_tool_python --no-index --find-links=file:///PATHTOINSTALLFILES)

I have to use
!pip install language_tool_python --no-index --find-links=file:///language_tool_python-2.7.1-py3-none-any.whl

If I try your code, I get

_Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -n_

Any advice?

**Comment by pyagoubi** [comment]
I'm having the same issue

I have tried your approach but I'm getting the same error as before. Could you please specify which cache I should move the files to? Is ist the directory of the language-tool library? Thats where I moved it.

Thanks!

**Comment by Zhao-Qiao** [comment]
I downloaded LanguageTool{version}.zip and moved the unzipped folder to  `~/.cache/language_tool_python/' and it works.
Hope that would help. @pyagoubi

**Comment by Zhao-Qiao** [comment]
> I'm having the same issue
> 
> I have tried your approach but I'm getting the same error as before. Could you please specify which cache I should move the files to? Is ist the directory of the language-tool library? Thats where I moved it.
> 
> Thanks!

I downloaded LanguageTool{version}.zip and moved the unzipped folder to `~/.cache/language_tool_python/' and it works.
Hope that would help.

**Comment by Dabirius** [comment]
@pyagoubi it was the same path @Zhao-Qiao mentioned above.

**Comment by pidefrem** [comment]
@jxmorris12 it should be fixed now.
The user now can use `LTP_JAR_DIR_PATH` as mentioned in the README to specify local installation and bypass the download for sure.
