### ISSUE TITLE
Execution time is too high

### ISSUE THREAD

**Issue by ehassan66** [jxmorris12/language_tool_python#59]
Then execution time of **matches = tool.check(text)** is too high. 
I am checking a string which contain 100 characters but its take 25-30 second to execute. 
sis this normal behavior or can we improve this ?

**Comment by ehassan66** [comment]
Yes Jack, Its so slow.
Actualaly i was trying with
tool = language_tool_python.LanguageTool('en-US')
BUt then itried with tool = language_tool_python.LanguageTool('en-US')  and its working fine.
Thanks
________________________________

**Comment by jxmorris12** [comment]
Sorry, what's the difference? Those two statements look the same!

**Comment by ehassan66** [comment]
Sorry Jack. I forgot to change the method.

Actually, first method is.
tool = language_tool_python.LanguageTool('en-US')
Second is.
tool = language_tool_python.LanguageToolPublicApi('en-US').

Fiest method is taking more time and second is less. Of course, it's due to API.

But i think still need to increase processing time.

Thanks,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
