### ISSUE TITLE
language_tool_python.LanguageToolPublicAPI   VS language_tool_python.LanguageTool

### ISSUE THREAD

**Issue by Gallo00** [jxmorris12/language_tool_python#60]
What's the difference between doing
tool = language_tool_python.LanguageTooI( lang)
tool.check(text)

and

tool = language_tool_python.LanguageToolPublicAPI( lang)
tool.check(text)
???

These 2 codes look doing samething but the second one is faster

**Comment by Gallo00** [comment]
Ehm, sorry I wanted to say that 
tool = language_tool_python.LanguageToolPublicAPI( lang)
tool.check(text)
is faster

**Comment by jxmorris12** [comment]
Sorry I should've said, I'm surprised that the second one is faster! But I think that's because you're checking a single text. If you check 100 or maybe even 10 texts, I still expect the first to be faster.
