### ISSUE TITLE
Use custom rules

### ISSUE THREAD

**Issue by CGarces** [jxmorris12/language_tool_python#61]
Hi.

I'm trying to use my own custom rules to analyze one document.

In the developer documentation recommends modify directly the grammar.xml file.
https://dev.languagetool.org/development-overview
another option is modify the  grammar.xml to add an external file.
https://dev.languagetool.org/tips-and-tricks

I need to modify the grammar.xml or there is another way supported by the python library?

**Comment by jxmorris12** [comment]
Hi! You'll have to modify the grammar.xml directly to add rules to the LanguageTool implementation. `language_tool_python` is an interface with LanguageTool, but can't directly modify it.

If you're implementing the rules yourself, though, why not write them in pure python and apply them in addition to a LanguageTool check?

**Comment by CGarces** [comment]
> Hi! You'll have to modify the grammar.xml directly to add rules to the LanguageTool implementation. `language_tool_python` is an interface with LanguageTool, but can't directly modify it.
> 
> If you're implementing the rules yourself, though, why not write them in pure python and apply them in addition to a LanguageTool check?

Thanks for the suggestion 

In this development the people that code the solution is different than the people that made the rules. I', not sure if they have python skills.

I'll think about it. My plan B is use [this approach](https://github.com/jxmorris12/language_tool_python/issues/30) to generate a docker file with custom rules.

After download the java LanguageTool I'll replace the grammar.xml file before launch my batch process.

**Comment by jxmorris12** [comment]
Ok great! Let me know if you run into any issues @CGarces

**Comment by sadi304** [comment]
> Hi! You'll have to modify the grammar.xml directly to add rules to the LanguageTool implementation. `language_tool_python` is an interface with LanguageTool, but can't directly modify it.
> 
> If you're implementing the rules yourself, though, why not write them in pure python and apply them in addition to a LanguageTool check?

Hi, @jxmorris12 any example for this you mentioned? You meant using a different tool like nltk or spacy etc to handle these or somehow we can get tokens and use it?
