### ISSUE TITLE
Adding full stops

### ISSUE THREAD

**Issue by Artucuno** [jxmorris12/language_tool_python#62]
Hey, I was just wondering if there is a way to automatically add full stops? (.)

**Comment by jxmorris12** [comment]
@Artucuno I'm not sure, sorry. You can check the LanguageTool forum: https://community.languagetool.org/rule/list?lang=en

**Comment by Artucuno** [comment]
Hey, I've found the rule that I need. How do I add it?

**Comment by Artucuno** [comment]
@jxmorris12

Issue didn't reopen so ima just @ you

**Comment by jxmorris12** [comment]
@Artucuno awesome! Well the short answer is that this rule should already be integrated into LanguageTool, and active by default, so if you correct some text using `language_tool_python` then the full stops rule should be included in corrections made by the tool.

**Comment by Artucuno** [comment]
Oh, it's not adding fullstops anyway. I am creating video subtitles using speech recognition and then using `language_tool_python` to add punctuation and stuff but there are no fullstops or commas for some reason.

**Comment by Artucuno** [comment]
I can send you the subtitles that it is trying to fix if you would like

**Comment by jxmorris12** [comment]
Try the grammar checker on the homepage: https://languagetool.org/ is it doing what you want? If not, LanguageTool just can't detect your errors for some reason

**Comment by jxmorris12** [comment]
feel free to reopen if something is going wrong with the python package
