### ISSUE TITLE
How to use a text file (containing paragraphs or conversations) for full analysis?

### ISSUE THREAD

**Issue by ls-milkyway** [jxmorris12/language_tool_python#67]
Hi !
**Feedback:** Indeed, a nice python wrapper for the language tool !

I just wanted to know the limitations of the tool? Is it meant for single sentences only?

1) Can I just put all the sentences in a text file under single quotes i.e 
 a) ' .....sentence 1...' 
 b) ' .....sentence 2...' 
       .....
       ....    so on to perform full grammar & spell analysis of the text file.

OR

2) Convert all the paragraphs & conversations into a single sentence under single quotes i.e ' ...all text.....' to perform full grammar & spell analysis.....Which one will be more better and accurate?
Actually, I have tried (1) using code:
```python
import language_tool_python
tool = language_tool_python.LanguageTool('en-US')
with open("output.txt", "a", encoding='utf8') as f:
     with open('input.txt', encoding='utf8') as f1:
          for line in f1:
              print((tool.correct(line.strip())), file=f)
tool.close() # explicitly shut off the LanguageTool
```
But I feel this may not be appropriate for full/whole analysis of the text file....specially if it is a full story or a full conversation.
Kindly suggest.

**Comment by jxmorris12** [comment]
Hi @ls-milkyway, I think your code is basically right. 

You can see [this page which discusses API limitations](https://languagetool.org/http-api/#:~:text=maximum%20number%20of%20characters%20per,free)%20%2F%2060%2C000%20(Premium)) for information about max query count and maximum length. Unfortunately, the LT API doesn't support calls in batch, so you have to make calls one-text-at-a-time. You can confirm this by checking, for example, [the endpoint for check()](https://languagetool.org/http-api/#!/default/post_check), which takes a single `text` parameter (i.e. not a list).

**Comment by jxmorris12** [comment]
let me know if I can help more in any way

**Comment by ls-milkyway** [comment]
> Hi @ls-milkyway, I think your code is basically right.
> 
> You can see [this page which discusses API limitations](https://languagetool.org/http-api/) for information about max query count and maximum length. Unfortunately, the LT API doesn't support calls in batch, so you have to make calls one-text-at-a-time. You can confirm this by checking, for example, [the endpoint for check()](https://languagetool.org/http-api/#!/default/post_check), which takes a single `text` parameter (i.e. not a list).

Thanks for the links...sorry for not being able to explain my question clearly....yep I will have to go premium ...but before I need to evaluate the tool's performance for... say a bunch of sentences in text file (within free trail API limit)......hence the 2 basic questions are (I am trying to be as clear as possible):

1) If all the sentence have different grammar syntax (say first person; present tense past tense etc.) ....and these sentence are not linked much to each other in the text file (they may or may not be a part of a story or a conversation)...in such a case per sentence analysis is the best solution and can be easily done using above mentioned code.

But What should be the approach or the python code if?

2) All the sentences are (as a whole) belongs to a conversation or a story, collectively ....how can I use the tool effectively in such a case (within API limits for analysis)..for eg.

Sentence 1: Bill: Where did Jack went?
Sentence 2: Martha replied that he go to see his wife.

So, per sentence analysis will correct Sentence 1 & 2

Sentence 1: Bill: Where did Jack go?
Sentence 2: Martha replied that he went to see his wife.

But collectively both the sentences should be:

Bill: Where did Jack go?
Martha: He went to see his wife.

As, sentence 2 is the part of the conversation, can the tool make such minor adjustments? or the majors ones if we consider a different example with more deviance?
I hope you got my point.
