### ISSUE TITLE
JSON-Decode-Error

### ISSUE THREAD

**Issue by LeonHammerla** [jxmorris12/language_tool_python#68]
Since a few days i get this Error:

- requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
- language_tool_python.utils.LanguageToolError: Error: Internal Error: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence

**Comment by jxmorris12** [comment]
@LeonHammerla - can you provide more details? What version, what command are you running, etc.? 

I just installed the package on a fresh VM through Google Colab and it seemed to work fine ([link](https://colab.research.google.com/drive/1qLnT2X6EnUJ9KgZnS36MvFJyeSLr6TdH?usp=sharing)).

**Comment by LeonHammerla** [comment]
my usage:

config = {'cacheSize': 5000,
                  'pipelineCaching': True,
                  'maxCheckThreads': multiprocessing.cpu_count()}

        
        config['fasttextBinary'] = os.path.join(ROOT_DIR, "data", "fasttext", "cc.de.300.bin")

        grammar_tool = language_tool_python.LanguageTool("de-DE",
                                                              config=config)

        grammar_tool.disabled_rules = ['COMMA_PARENTHESIS_WHITESPACE']


loading works just fine, but when i try to perform a check i get the EROOR described above:
(and it did work before without me changing code)

matches = grammar_tool.check(sent)

**Comment by LeonHammerla** [comment]
it doesnt even work with minimal config like:

grammar_tool = language_tool_python.LanguageTool("de-DE")

(same ERROR)

**Comment by LeonHammerla** [comment]
1) I also tried to pip uninstall and install again 
2) also uninstalled and installed the language-tool 5.7 part that gets downloaded and stored in .cache

**Comment by LeonHammerla** [comment]
The Error was due to not enough disk space on my end. So the problem is solved.
thx

**Comment by jxmorris12** [comment]
thanks for following up!
