### ISSUE TITLE
Enable MISSING_VERB rule

### ISSUE THREAD

**Issue by alexschrade** [jxmorris12/language_tool_python#71]
I am looking to enable the MISSING_VERB rule, which is disabled on default on LanguageTool. How do I do that? I've tried setting the object property, but it didn't work unfortunately:

`tool = language_tool_python.LanguageTool("de-DE")
tool.enabled_rules="MISSING_VERB"`

**Comment by jxmorris12** [comment]
`enabled_rules` is a set. can you try `tool.enabled_rules.add("MISSING_VERB")`?

**Comment by alexschrade** [comment]
That did it, thank you very much.
