### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ZaydH** [jxmorris12/language_tool_python#74]
I do not see a Citation file for this repo.  Do you have a preferred citation?  Once you let me know, I can create a pull request to add the citation as a `bibtex` file so Github can detect it.

**Comment by jxmorris12** [comment]
Hi @ZaydH -- thanks for asking. You don't need to cite my software. You can just cite the original LanguageTool:

A Rule-Based Style and Grammar Checker (Naber, 2003) -- http://www.danielnaber.de/languagetool/download/style_and_grammar_checker.pdf

**Comment by ZaydH** [comment]
Thanks for the confirmation.  We will do that.
