### ISSUE TITLE
Are there any plans to update the version of the langauge tool that is being used in this repo>

### ISSUE THREAD

**Issue by jkyndir** [jxmorris12/language_tool_python#82]
The latest LT version is 6.3, no longer V 5.7.

**Comment by jkyndir** [comment]
i figured it out. you can just change the `LATEST_VERSION = '5.7'` to 6.3 in the download_lt.py

**Comment by pidefrem** [comment]
@jkyndir you can also use the environment variable `LTP_PATH` and download the latest version from here: https://languagetool.org/download/.

**Comment by jxmorris12** [comment]
thanks @pidefrem :)
