### ISSUE TITLE
Disabling spell check = HTTP Error 400?

### ISSUE THREAD

**Issue by maxiedaniels** [jxmorris12/language_tool_python#9]
I'm trying to disable spell checking, but when I do, I get `language_tool_python.utils.LanguageToolError: http://127.0.0.1:8081/v2/: HTTP Error 400: Bad Request`.

Code is:
tool = language_tool_python.LanguageTool('en-GB')
tool.disable_spellchecking()
tool.correct(somestringhere)

**Comment by jxmorris12** [comment]
Hi @maxiedaniels -- thanks for explaining this so clearly. And thanks for using `language_tool_python`!

I think I fixed the spell-checking issue in the new version, 2.2.2. I've also added a test to ensure this issue doesn't arise again.

You can upgrade via `pip install language_tool_python --upgrade`. Please let me know if that fixed it.
